In [35]:
# 5. Тест в разделе (Задача предстказания, линейная регрессия)
# Step 5.6 #1
import numpy as np
import pandas as pd
from sklearn.metrics import mean_absolute_error as mae
from sklearn.metrics import mean_absolute_percentage_error as mape
df = pd.DataFrame(data={'Нецелевые признаки': [',,,']*10,
                  'Y':  [1.0, 2.0, 3.0, 4.0, 5.0, -1.0, -2.0, -3.0, -4.0, -5.0],
                  "Y'": [0.0, 2.0, 2.0, 5.0, 3.0, -1.0, -1.0, -4.0, -6.0, -5.0]},
                  index=['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'],
                  )
print(f"""mae: {mae(df["Y"], df["Y'"])}""")
print(f"""mape: {round(mape(df["Y"], df["Y'"]) * 100)}""")

# Step 5.6 #2
from sklearn import linear_model as lm
# Create linear regression object
lr = lm.LinearRegression()
lr.fit([[0],[1],[2],[3]], [0,1,0,3])
print("Intercept: ", lr.intercept_)
print("Coefficient: ", lr.coef_)

# Step #5.7
from sklearn.linear_model import Ridge
import numpy as np
alpha=1.0
X = np.array( [ [0,3], [1,2], [2,1], [3,0] ] )
y = np.array( [ 0, 1, 0, 3 ] )
#expand X by 1.0 column
X = np.insert(X, 0, values=1, axis=1 )
model = Ridge(alpha=alpha, fit_intercept=False )
model.fit(X, y )

print("coef:", model.coef_);

mae: 0.9
mape: 33
Intercept:  -0.20000000000000018
Coefficient:  [0.8]
[[1 0 3]
 [1 1 2]
 [1 2 1]
 [1 3 0]]
coef: [ 0.17391304  0.62450593 -0.1027668 ]
